# Generated by Django 3.2.4 on 2021-06-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='titulo',
            field=models.CharField(default='zapatos', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
